### ISSUE TITLE
Not connecting to Discord

### ISSUE THREAD

**Issue by xhxnna** [leonardssh/vscord#100]
For whatever reason the extension is not connecting to Discord anymore, tried looking at extension logs and couldn't find anything.

**Comment by xhxnna** [comment]
Downgrading to version 4.5.0 (released 8 months ago) seems to fix it, so it's something with a recent update.

**Comment by nick22985** [comment]
Getting the same issue. Seems like the rpc will just timeout allot. @xhxnna if you go to output then select the rpc dropdown what does your logs say?

Sometimes this timeouts and other times it does not maybe some sort of rate limit or something? Weird how downgrading fixes
```
[9:01:45 pm - INFO] Reconnecting to Discord Gateway...
[9:01:45 pm - INFO] [003] Destroyed Discord RPC client
[9:01:52 pm - INFO] Reconnecting to Discord Gateway...
[9:01:52 pm - INFO] [003] Destroyed Discord RPC client
[9:01:55 pm - ERROR] Encountered following error while trying to login:
RPC_CONNECTION_TIMEOUT: Connection timed out
[9:01:55 pm - INFO] [002] Destroyed Discord RPC client
[9:01:58 pm - INFO] Reconnecting to Discord Gateway...
[9:01:58 pm - INFO] [003] Destroyed Discord RPC client
[9:02:02 pm - ERROR] Encountered following error while trying to login:
RPC_CONNECTION_TIMEOUT: Connection timed out
[9:02:02 pm - INFO] [002] Destroyed Discord RPC client
[9:02:08 pm - ERROR] Encountered following error while trying to login:
RPC_CONNECTION_TIMEOUT: Connection timed out
[9:02:08 pm - INFO] [002] Destroyed Discord RPC client

```

**Comment by xhxnna** [comment]
Looks to be the same behavior on my end

**Comment by xhayper** [comment]
Weird, timeout is caused by not being able to find the IPC path to connect to,
can you tell me your OS? Discord version (flatpak or snapstore)

**Comment by xhayper** [comment]
Huh, i am starting to get it too, i think it's something with the presence.

**Comment by xhayper** [comment]
![image](https://user-images.githubusercontent.com/46065349/196586119-fb0fd3ed-87b4-4ab9-9e30-93f956f8f79f.png)

**Comment by xhayper** [comment]
very sorry for late response!

**Comment by xhayper** [comment]
I gonna rewrite the controller for the RPC since it's really wonky.

**Comment by xhayper** [comment]
https://github.com/leonardssh/vscord/tree/feat/controller

**Comment by xhxnna** [comment]
This seems to be broken when using it within WSL on Windows 11:
![image](https://user-images.githubusercontent.com/46457601/196942510-ce79fd2f-4281-472b-8561-788521688ae4.png)
```
[2022-10-20 07:59:06.040] [exthost] [error] Error: ENOENT: no such file or directory, stat '\home\hanna\projects\leaf\src\lang.zig'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at Ha.get fileSize [as fileSize] (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:31962)
    at Hc (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:29909)
    at Vt (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:38801)
    at gl (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:36811)
    at Jt.sendActivity (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:2637)
    at Jt.enable (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:2991)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:4925
    at n._executeContributedCommand (c:\Users\Hanna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:111316) rpc.reconnect {"value":"LeonardSSH.vscord","_lower":"leonardssh.vscord"
```

**Comment by xhayper** [comment]
open a brand new issue please, thanks!
