### ISSUE TITLE
Extension unable to find files in VMs, SSH, or WSL

### ISSUE THREAD

**Issue by xhxnna** [leonardssh/vscord#108]
![image](https://user-images.githubusercontent.com/46457601/196942510-ce79fd2f-4281-472b-8561-788521688ae4.png)
```
[2022-10-20 07:59:06.040] [exthost] [error] Error: ENOENT: no such file or directory, stat '\home\hanna\projects\leaf\src\lang.zig'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at Ha.get fileSize [as fileSize] (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:31962)
    at Hc (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:29909)
    at Vt (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:38801)
    at gl (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:17:36811)
    at Jt.sendActivity (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:2637)
    at Jt.enable (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:2991)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.4\dist\extension.js:18:4925
    at n._executeContributedCommand (c:\Users\Hanna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:111316) rpc.reconnect {"value":"LeonardSSH.vscord","_lower":"leonardssh.vscord"
```

_Originally posted by @xhxnna in https://github.com/leonardssh/vscord/issues/100#issuecomment-1285404369_

**Comment by xhayper** [comment]
i gonna push 4.6.5 our with sourcemap so we can figure out what happened

**Comment by xhayper** [comment]
@espenja

**Comment by xhayper** [comment]
i published version with source map, it show show stuff correctly now

**Comment by xhxnna** [comment]
From the `Extension Host` output:
```
[2022-10-20 08:47:34.761] [exthost] [error] Error: ENOENT: no such file or directory, stat '\home\hanna\projects\leaf\src\lang.zig'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at Ha.get fileSize [as fileSize] (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\data.ts:67:19)
    at getFileSize (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\helpers\getFileSize.ts:7:20)
    at details (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\activity.ts:220:26)
    at activity (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\activity.ts:70:15)
    at Jt.sendActivity (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\controller.ts:138:22)
    at Jt.enable (c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\controller.ts:156:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\Hanna\.vscode\extensions\leonardssh.vscord-4.6.5\src\extension.ts:81:9
    at n._executeContributedCommand (c:\Users\Hanna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:111316) rpc.reconnect {"value":"LeonardSSH.vscord","_lower":"leonardssh.vscord"}
    ```

**Comment by xhayper** [comment]
yup, so the data PR that espenja made broke the extenstion for wsl

**Comment by xhayper** [comment]
I gonna push 4.6.6 out which will not return file size when it error out as a temporary fix, we will have to find more permenant fix

**Comment by xhxnna** [comment]
Sounds good to me

**Comment by nick22985** [comment]
@xhayper seems like it is just permanently broken now

**Comment by xhayper** [comment]
ah fuck, we need break point

**Comment by xhayper** [comment]
I ACCIDENTLY SET ENABLED TO FALSE, OH MY GOD

**Comment by xhayper** [comment]
![image](https://user-images.githubusercontent.com/46065349/196966172-28652c93-21f9-4153-8612-1fd152c3720f.png)

**Comment by xhayper** [comment]
( it was false before)

**Comment by nick22985** [comment]
oof

**Comment by xhayper** [comment]
fixed it in 4.6.7, published

**Comment by nick22985** [comment]
yep can confirm is working again xD

**Comment by espenja** [comment]
Oh damn, I missed all the action! Glad you found a temporary fix, @xhayper! Speedy delivery! I don't have the time to investigate a solution to this for a while.
