### ISSUE TITLE
Presence not showing up.

### ISSUE THREAD

**Issue by japandotorg** [leonardssh/vscord#111]
Discord Presence is not showing up even tho it's clearly showing "Connected to Discord".
Been working fine until today, suddenly it decided to disappear on it's own, thought something was wrong with the session but even restarting VSC with another folder didn't work. Even tried reinstalling the extension, but no luck either.

Version Info -
Visual Studio Code Insider - `1.73.0-insider (user setup)`
OS - `Windows 11 Education: 22H2 (OS Build 22621.674)`
Discord - `Canary 153314 (e777c2c)` 
VSCORD - `latest`

![image](http://i.melonbot.io/500.png)

**Comment by nick22985** [comment]
@japandotorg Any errors in output rpc?

**Comment by japandotorg** [comment]
I'm out of station right now and will get access to my pc and internet on monday most probably, I'll check the output rpc and inform about it here as soon as I can get access to my pc again.

**Comment by DarthGigi** [comment]
I'm having the same problem

Visual Studio Code - Version: 1.72.2
OS - macOS Ventura 13.0 (22A380)
Discord - Stable 154186 (fccec91), Host 0.0.269
VSCORD - 5.0.5

**Comment by xhayper** [comment]
@DarthGigi please enable debug mode and send the output

**Comment by DarthGigi** [comment]
It seems like it works again, I don't know why and I haven't changed anything.

**Comment by getlaurekt** [comment]
I had the same issue, but I was using Crawl version before for so many years, but for some reasons it wasn't showing astro files even tho it was implemented, so I decided to install this rpc version and I had problems with it even after disabling Crawl one, but after totally uninstalling and restarting everything every single time i uninstalled something it started to work, really weird.

**Comment by xhayper** [comment]
this extenstion is hauntged

**Comment by xhayper** [comment]
this extenstion is just pursed haunted

**Comment by DarthGigi** [comment]
It for some reason no longer works, but this time I am getting an error in the logs:

<details>
<summary>Error Log:</summary>

> [3:39:26 PM] [INFO] Discord Rich Presence for VS Code activated.
> [3:39:26 PM] [INFO] Registered Discord Rich Presence commands
> [3:39:36 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
>     at qa.login (/Users/gigi/.vscode/extensions/leonardssh.vscord-5.0.8/node_modules/@xhayper/discord-rpc/dist/Client.js:250:20)
>     at new Zi (/Users/gigi/.vscode/extensions/leonardssh.vscord-5.0.8/src/controller.ts:34:14)
>     at Object.<anonymous> (/Users/gigi/.vscode/extensions/leonardssh.vscord-5.0.8/src/extension.ts:10:20)
>     at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
>     at Module.load (node:internal/modules/cjs/loader:1035:32)
>     at Module._load (node:internal/modules/cjs/loader:876:12)
>     at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
>     at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
>     at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
>     at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
>     at Module.require (node:internal/modules/cjs/loader:1059:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
>     at p._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:66574)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Promise.all (index 0)
> [3:39:36 PM] [INFO] [002] Destroyed Discord RPC client

</details>

**Comment by noxzym** [comment]
I got this error when change the deprecated json key
```bash
2022-11-05 05:46:36.745 [error] TypeError: Cannot read properties of undefined (reading 'slice')
    at replaceAppInfo (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:262:17)
    at replaceAllText (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:129:32)
    at dl (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:167:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Zi.sendActivity (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\controller.ts:159:22)
    at Zi.enable (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\controller.ts:177:9)
    at c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\extension.ts:102:9
    at s._executeContributedCommand (c:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:111367) vscord.reconnect {"value":"LeonardSSH.vscord","_lower":"leonardssh.vscord"}
```

**Comment by nick22985** [comment]
The slicing is a cleanup thing shouldn't really have a effect on the extension not working.

**Comment by nick22985** [comment]
> I got this error when change the deprecated json key
> 
> ```shell
> 2022-11-05 05:46:36.745 [error] TypeError: Cannot read properties of undefined (reading 'slice')
>     at replaceAppInfo (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:262:17)
>     at replaceAllText (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:129:32)
>     at dl (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\activity.ts:167:35)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Zi.sendActivity (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\controller.ts:159:22)
>     at Zi.enable (c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\controller.ts:177:9)
>     at c:\Users\lenovo\.vscode\extensions\leonardssh.vscord-5.0.8\src\extension.ts:102:9
>     at s._executeContributedCommand (c:\Users\lenovo\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:111367) vscord.reconnect {"value":"LeonardSSH.vscord","_lower":"leonardssh.vscord"}
> ```

#149 should stop this

**Comment by ellaeslaflaca** [comment]
Hi, I am having the same issue: It is not showing presence on Discord **with java files**. It still works fine with html, css, js, and python files. Not sure why it is not detecting the java file. 

VSC- 1.74.3 
OS - Mac Ventura 13.0.1
Discord - Desktop App 0.0.269

**Comment by boldandbrad** [comment]
I'm experiencing a similar issue. Can't get presence to show for any files.

VSCodium - 1.75.0 (installed via brew)
OS - macOS Ventura 13.2
Discord - 0.0.272 (installed via brew)
Vscord - 5.0.18

The extension claims it is connected to discord but my presence never updates.

I've tried reinstalling the extension, as well as restarting both VSCodium and Discord.

**Comment by xhayper** [comment]
We need log for this, turn on debug mode too

**Comment by boldandbrad** [comment]
<details>
<summary>some debug logs</summary>

[10:42:31 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[10:42:31 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileName(): setup
[10:42:31 PM] [INFO] [data.ts] fileExtension(): .py
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileName(): setup
[10:42:31 PM] [INFO] [data.ts] fileExtension(): .py
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileName(): setup
[10:42:31 PM] [INFO] [data.ts] fileExtension(): .py
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy
[10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
  "uri": {
    "$mid": 1,
    "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli",
    "path": "/Users/bradleywojcik/Developer/repos/makey-cli",
    "scheme": "file"
  },
  "name": "makey-cli",
  "index": 0
}
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] fileSize(): 1359
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli
[10:42:31 PM] [INFO] [data.ts] fileName(): setup
[10:42:31 PM] [INFO] [data.ts] fileExtension(): .py
[10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {

</details>

first couple lines look fishy to me but everything else looks like what I would expect.

**Comment by xhayper** [comment]
seems like you're using a mac.... hmmm does that have smth to do with this...? on my mac it's fine....

**Comment by boldandbrad** [comment]
I'm sorry I don't understand. Why would it matter that I'm using a mac? Isn't this supposed to work on mac?

**Comment by xhayper** [comment]
I am not aure

**Comment by ellaeslaflaca** [comment]
I am unsure if anything was done but I thought I'd let you all know that today it is working finally and it shows presence with java files.

**Comment by xhayper** [comment]
We didn't do anything... and it works...? huh..

**Comment by xhayper** [comment]
<img width="515" alt="Screenshot 2023-02-09 at 08 56 44" src="https://user-images.githubusercontent.com/46065349/217697215-6609c3b7-7811-4c71-b203-5860427ef776.png">

It works on my mac too, this is very weird

**Comment by xhayper** [comment]
> some debug logs
> [10:42:31 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor [10:42:31 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output' [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileName(): setup [10:42:31 PM] [INFO] [data.ts] fileExtension(): .py [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileName(): setup [10:42:31 PM] [INFO] [data.ts] fileExtension(): .py [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileName(): setup [10:42:31 PM] [INFO] [data.ts] fileExtension(): .py [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] dirName(): makey-cli [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] gitBranchName(): feature/9-no-copy [10:42:31 PM] [INFO] [data.ts] gitRemoteUrl(): Url: https://github.com/boldandbrad/makey-cli.git [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI { "uri": { "$mid": 1, "fsPath": "/Users/bradleywojcik/Developer/repos/makey-cli", "external": "file:///Users/bradleywojcik/Developer/repos/makey-cli", "path": "/Users/bradleywojcik/Developer/repos/makey-cli", "scheme": "file" }, "name": "makey-cli", "index": 0 } [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] fileSize(): 1359 [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] workspaceName(): makey-cli [10:42:31 PM] [INFO] [data.ts] fileName(): setup [10:42:31 PM] [INFO] [data.ts] fileExtension(): .py [10:42:31 PM] [INFO] [data.ts] workspaceFolder(): Found URI {
> 
> first couple lines look fishy to me but everything else looks like what I would expect.

Also this implies that everything works correctly, which is weird.

**Comment by xhayper** [comment]
@boldandbrad there's an option for more verbose log in the extension setting called "debug", could you enable that and send the log again?

**Comment by boldandbrad** [comment]
I reinstalled discord twice and now it works... I have no idea why it wasn't working before. But I don't think it was vscord's fault. Thank you for your help.

**Comment by Mopsgamer** [comment]
If you don't mind, I suggest closing this issue in favor of #343.
