### ISSUE TITLE
Couldn't connect to Discord via RPC:

### ISSUE THREAD

**Issue by KuezyIT** [leonardssh/vscord#145]
I tried to use vscord but when trying to edit code it says:
`Couldn't connect to Discord via RPC: RPC_CONNECTION_TIMEOUT: Connection timed out`

I do have the necessary settings enabled in discord:
![image](https://user-images.githubusercontent.com/101394236/202863784-b6e03f30-9167-4b17-a83a-3b57c5af9442.png)

Heres the exact error log:
```js
[6:23:15 PM] [INFO] Discord Rich Presence for VS Code activated.
[6:23:15 PM] [INFO] Registered Discord Rich Presence commands
[6:23:25 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
    at Ma.login (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.10\node_modules\@xhayper\discord-rpc\dist\Client.js:250:20)
    at new Qi (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.10\src\controller.ts:34:14)
    at Object.<anonymous> (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.10\src\extension.ts:10:20)
    at Module.u._compile (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:13363)
    at Function.w._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:61309)
    at Function.v._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:60713)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
    at d.rb (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:62572)
    at async Promise.all (index 0)
[6:23:25 PM] [INFO] [002] Destroyed Discord RPC client
[6:23:25 PM] [INFO] Successfully logged in to Discord with client ID 782685898163617802
```

When looking at the discord client ID it says `782685898163617802` which is not my client id...

**Comment by xhayper** [comment]
Client ID is the id that VSCord use, not user id.

**Comment by xhayper** [comment]
Can you enable debug mode and send me the log?

**Comment by xhayper** [comment]
Alright i am getting this bug too

**Comment by xhayper** [comment]
alright you can try reconnecting it if it happened

**Comment by KuezyIT** [comment]
And how can I reconnect the extension in VS code?

**Comment by xhayper** [comment]
ctrl + sift + p and there should be a reconmect command

**Comment by KuezyIT** [comment]
![image](https://user-images.githubusercontent.com/101394236/202909138-12344c08-94c3-4998-9585-c8c210111e88.png)

Just tried to reconnect, still doesnt work.. :(

**Comment by xhayper** [comment]
restart you discord then reconnect, see id it work

**Comment by KuezyIT** [comment]
![image](https://user-images.githubusercontent.com/101394236/202909570-ec0158b0-5e98-4ef1-b6fb-02c2bff813c3.png)
After restarting discord and then reconnecting via STRG + SHIFT + P and then selecting reconnecting to discord gateway I get the same error message..

**Comment by xhayper** [comment]
what the hell... this is so weird, another weird bug to the list, you can try debug mode to see if it works

**Comment by xhayper** [comment]
what the hell... this is so weird, another weird bug to the list, you can try debug mode to see if it works

**Comment by KuezyIT** [comment]
Uhh, if I just would know how to debug extensions xddd

**Comment by xhayper** [comment]
its in settings

**Comment by KuezyIT** [comment]
Yep, got it. Here you go:

```
[6:19:34 PM] [INFO] [data.ts] ext(): Extension
[6:19:34 PM] [INFO] [data.ts] ext(): Changed to Extension
[6:19:34 PM] [INFO] [data.ts] [data.ts] ext(): Git extension is active
[6:19:34 PM] [INFO] [data.ts] api(): true
[6:19:34 PM] [INFO] [data.ts] api(): gitApi
[6:19:34 PM] [INFO] [data.ts] updateGit()
[6:19:34 PM] [INFO] [data.ts] gitRepoPath(): 
[6:19:34 PM] [INFO] [data.ts] updateGit(): repo 
[6:19:34 PM] [INFO] [data.ts] api(): true
[6:19:34 PM] [INFO] [data.ts] api(): gitApi
[6:19:34 PM] [INFO] [data.ts] updateGit()
[6:19:34 PM] [INFO] [data.ts] gitRepoPath(): 
[6:19:34 PM] [INFO] [data.ts] updateGit(): repo 
[6:19:34 PM] [INFO] Discord Rich Presence for VS Code activated.
[6:19:34 PM] [INFO] Registered Discord Rich Presence commands
[6:19:34 PM] [INFO] [data.ts] listeners(): Open Repo CUDA-Systembot
[6:19:34 PM] [INFO] [data.ts] updateGit()
[6:19:34 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:34 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:34 PM] [INFO] [data.ts] listeners(): Open Repo CUDA-Systembot
[6:19:34 PM] [INFO] [data.ts] updateGit()
[6:19:34 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:34 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:35 PM] [INFO] [data.ts] listeners(): Change State initialized
[6:19:35 PM] [INFO] [data.ts] updateGit()
[6:19:35 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:35 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:35 PM] [INFO] [data.ts] listeners(): Change State initialized
[6:19:35 PM] [INFO] [data.ts] updateGit()
[6:19:35 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:35 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\00 System Builds\CUDA-Systembot
[6:19:44 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:19:44 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:19:44 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
    at za.login (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.11\node_modules\@xhayper\discord-rpc\dist\Client.js:250:20)
    at new en (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.11\src\controller.ts:34:14)
    at Object.<anonymous> (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.11\src\extension.ts:10:20)
    at Module.u._compile (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:13370)
    at Function.w._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:61374)
    at Function.v._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:60776)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
    at d.rb (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:62638)
    at async Promise.all (index 0)
[6:19:44 PM] [INFO] [002] Destroyed Discord RPC client
[6:19:44 PM] [INFO] Successfully logged in to Discord with client ID 782685898163617802
[6:19:57 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:19:57 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:19:59 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:19:59 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:20:00 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:20:00 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:20:13 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:20:13 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:21:49 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:21:49 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
[6:21:49 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:21:51 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[6:21:51 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
```

**Comment by getlaurekt** [comment]
I have different bug, for me it was saying about not finding a command or sum when i tried to connect to the discord with command in vsc(similiar error what Kuezy got, but with not finding a command), even after restarting vsc or dc it doesnt really matter also the img at the bottom wasnt visible at all, smth is going wrong with this extension recently, so i switched back to crawl one, this one isnt useful at all atm, and i was using it cause of astro files

This is the error:
![image](https://user-images.githubusercontent.com/58201840/203461523-b84ff0f2-ab27-4cb8-88af-e7d8d9d037d0.png)
It happens to every command from vscord
No matter which of these etc i will use it the same, and same goes for restarting vsc or discord
![image](https://user-images.githubusercontent.com/58201840/203461596-e2e42b24-1b74-4f07-820d-d589b2a70e2d.png)
I have hope you will fix it somehow, its so annoying i havent had so many problems with any extension so far ;-;

**Comment by xhayper** [comment]
i know that it's super annoying and stuff, but i can't get it to re-produce it on my mac machine WHICH is really a bad sign on fixing this bug, i really can't figure out what cause it it all, i also use astro on my project and the same bug didn't happened.

I think this extension is haunted.

**Comment by xhayper** [comment]
same on my windows machine, everything just works, it's really weird.

**Comment by getlaurekt** [comment]
> i know that it's super annoying and stuff, but i can't get it to re-produce it on my mac machine WHICH is really a bad sign on fixing this bug, i really can't figure out what cause it it all, i also use astro on my project and the same bug didn't happened.
> 
> I think this extension is haunted.

The funniest part is that it did start to happen after one of updates, it's not like problem on my side that's the funniest part and I have no idea what does it happens. I also managed like 2 times to make it work, like the extension was running somehow, BUT after disconnecting it of discord etc i couldnt reconnect it no matter what cause I was getting the error that I did show you in my previous comment.

Ye, this extension has hard time ngl lie. I started to use it cause of Astro files, but welp I can't even use it anymore hah.

**Comment by getlaurekt** [comment]
> same on my windows machine, everything just works, it's really weird.

Stranger things I'd say then hah, it's so weird.

**Comment by xhayper** [comment]
I also have no idea on my side either

**Comment by nick22985** [comment]
Can use send your exact windows version and also the exact vscode / vscodium / vsinsider build numbers

you can get windows version by doing `win + r -> winver`
to get vscode version go to the toolbar click help and then about. 

Idk if I can recreate it by going to your version of things. But working fine for me on windows so semi confused why this is happening

**Comment by nick22985** [comment]
@xhayper to hackly recreate this you can just spam the hell outta disconnecting and reconnecting eventually you will get a error for disconnecting when going to reconnect it wont fully reconnect. It got something to do with the client not fully destorying the rpc when it errors. Making it stuck in a loop where it can send presence or reconnect because it is disabeld. 

Tryied to see if the `this.client.isConnected` but it is still true even after erroring.

A check could be added to `root(): window.onDidChangeActiveTextEditor` checking if any errors have occurred if so enable the extension again but have to make sure it doesn't actually do it when it is not meant to.

**Comment by xhayper** [comment]
when an error happened the whole discord rpc lib would die... right?

**Comment by nick22985** [comment]
Yes but no not when the timeout happens. It somehow doesnt

**Comment by nick22985** [comment]
> ![image](https://user-images.githubusercontent.com/101394236/202909570-ec0158b0-5e98-4ef1-b6fb-02c2bff813c3.png) After restarting discord and then reconnecting via STRG + SHIFT + P and then selecting reconnecting to discord gateway I get the same error message..

Im now getting this sometimes as well interesting
```
2022-11-26 11:57:39.227 [warning] UNRESPONSIVE extension host: 'leonardssh.vscord' took 39.19048481778833% of 296.351ms, saved PROFILE here: 'file:///c%3A/Users/nick/AppData/Local/Temp/exthost-b8983f.cpuprofile'
```

will send the log file to you @xhayper on discord as it doesn't wanna on here

**Comment by xhayper** [comment]
This is weird...

**Comment by getlaurekt** [comment]
After update on 27th the extension started to work again for me(i was surprised) but update on 29th fcked up it again, i have no idea whats going on, im getting the  same error again, im hopeless for this extension xD

**Comment by xhayper** [comment]
GAAAAAHHHHHH!!!!! THIS BUG HAUNTED ME EVERYDAY!!!

**Comment by nick22985** [comment]
😢

**Comment by nick22985** [comment]
> After update on 27th the extension started to work again for me(i was surprised) but update on 29th fcked up it again, i have no idea whats going on, im getting the same error again, im hopeless for this extension xD

All the time rlly? I wish I could recreate this with that consistently.

**Comment by KuezyIT** [comment]
Hey guys, just checkin' up on this issue. Any way to fix it so far?

**Comment by xhayper** [comment]
Nope, we are actively hunting for the source

**Comment by timof121** [comment]
Same here, running Arch. 
![image](https://user-images.githubusercontent.com/52547763/205450525-333aa476-0dfe-4a0c-9c03-23690d031230.png)

**Comment by xhayper** [comment]
its the timeout issue again....

**Comment by nick22985** [comment]
can use send logs on the latest version



> Same here, running Arch. ![image](https://user-images.githubusercontent.com/52547763/205450525-333aa476-0dfe-4a0c-9c03-23690d031230.png)

**Comment by KuezyIT** [comment]
> can use send logs on the latest version. Added a few new things to see if I can figure out what going on
> 
> > Same here, running Arch. ![image](https://user-images.githubusercontent.com/52547763/205450525-333aa476-0dfe-4a0c-9c03-23690d031230.png)

Thats what I've got (DEBUG OUTPUT):
```sh
[4:18:12 PM] [INFO] [data.ts] ext(): Extension
[4:18:12 PM] [INFO] [data.ts] ext(): Changed to Extension
[4:18:12 PM] [INFO] [data.ts] [data.ts] ext(): Git extension is active
[4:18:12 PM] [INFO] [data.ts] api(): true
[4:18:12 PM] [INFO] [data.ts] api(): gitApi
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): 
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo 
[4:18:12 PM] [INFO] [data.ts] api(): true
[4:18:12 PM] [INFO] [data.ts] api(): gitApi
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): 
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo 
[4:18:12 PM] [INFO] Discord Rich Presence for VS Code activated.
[4:18:12 PM] [INFO] Registered Discord Rich Presence commands
[4:18:12 PM] [INFO] [data.ts] listeners(): Open Repo RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] listeners(): Open Repo RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] listeners(): Change State initialized
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] listeners(): Change State initialized
[4:18:12 PM] [INFO] [data.ts] updateGit()
[4:18:12 PM] [INFO] [data.ts] gitRepoPath(): d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:12 PM] [INFO] [data.ts] updateGit(): repo d:\Users\Kuezy\04 Projects\[CUDA - DEVELOPMENT]\10 Develoment\30 Customer Builds\RyzenRP - Systembot
[4:18:15 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[4:18:15 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
[4:18:19 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[4:18:21 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[4:18:21 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
[4:18:22 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
    at $a.login (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.14\node_modules\@xhayper\discord-rpc\dist\Client.js:250:20)
    at new Zi (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.14\src\controller.ts:35:14)
    at Object.<anonymous> (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.14\src\extension.ts:10:20)
    at Module.u._compile (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:13379)
    at Function.w._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:61900)
    at Function.v._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
    at d.pb (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:63164)
    at async Promise.all (index 0)
[4:18:22 PM] [INFO] [002] Destroyed Discord RPC client
[4:18:22 PM] [INFO] Successfully logged in to Discord with client ID 782685898163617802
```

**Comment by getlaurekt** [comment]
> > After update on 27th the extension started to work again for me(i was surprised) but update on 29th fcked up it again, i have no idea whats going on, im getting the same error again, im hopeless for this extension xD
> 
> All the time rlly? I wish I could recreate this with that consistently.
> 
> How I was recreating this I have fixed and no longer does it so I have no way of reproducing this

Ye, update on 27th was working for me, IDK WHY, but the extension was working for the whole day of me coding, but on 29th the new update came out and the extension in my case came back to the error and didnt work at all.

If I can help you with sending some logs or something you can tell me how and where I can find them, so i will send yaa them maybe it will help you...

**Comment by Roxas-Alt** [comment]
ctrl + shift + p
Then use: "developer:reload Window"

**Comment by KuezyIT** [comment]
> ctrl + shift + p Then use: "developer:reload Window"
> 
> This fix the problem ( in my pc )

Nope, that did not fix the issue on my end..

**Comment by KuezyIT** [comment]
Hi, just checkin' up on this issue. Anything new as for now?

**Comment by Nitsua0615** [comment]
Had this issue for ages, uninstalled, re-installed, didn't fix it. Finally I decided to restart discord which fixed the issue

**Comment by xhayper** [comment]
That's timeout issue then... hmm

**Comment by nick22985** [comment]
```
Activating extension 'LeonardSSH.vscord' failed: Extension 'vscode.git' is not known or not activated.
$onExtensionActivationError @ workbench.desktop.main.js:2155
```
@xhayper

**Comment by nick22985** [comment]
So for anyone looking to help us in this could you please go to help > toggle dev tools and then find the error for `LeonardSSH.vscord`

**Comment by xhayper** [comment]
I found out there's a bug with discord-rpc have a bug where `disconnected` event is not called properly.

**Comment by xhayper** [comment]
that might explain why a lot of stuff just doesn't work when disconnected.

**Comment by xhayper** [comment]
98db028af5da06ef29f0926883bfae1d4e1b5643 should fix git issue.

**Comment by xhayper** [comment]
Reconnecting works now

**Comment by KuezyIT** [comment]
Hi - yes it works now on both my laptop and workstation. Thanks for helping!

**Comment by SirFluffDev** [comment]
Same issue for me, but only when I'm running VSCodium. Regular VSCode runs the extension fine.
I'm on the latest version of Pop!_OS.

**Comment by xhayper** [comment]
> Same issue for me, but only when I'm running VSCodium. Regular VSCode runs the extension fine.
> I'm on the latest version of Pop!_OS.

could you open your logs?

**Comment by SirFluffDev** [comment]
Here you go:
```[10:06:53 PM] [INFO] Discord Rich Presence for VS Code activated.
[10:06:53 PM] [INFO] Registered Discord Rich Presence commands
[10:07:03 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
    at $a.login (/home/luke/.var/app/com.vscodium.codium/data/codium/extensions/leonardssh.vscord-5.0.18-universal/node_modules/.pnpm/@xhayper+discord-rpc@1.0.15/node_modules/@xhayper/discord-rpc/dist/Client.js:250:20)
    at new Zi (/home/luke/.var/app/com.vscodium.codium/data/codium/extensions/leonardssh.vscord-5.0.18-universal/src/controller.ts:44:14)
    at Object.<anonymous> (/home/luke/.var/app/com.vscodium.codium/data/codium/extensions/leonardssh.vscord-5.0.18-universal/src/extension.ts:10:20)
    at Module.u._compile (/app/share/codium/resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/app/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
    at Function.w._load (/app/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
    at Function.v._load (/app/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (/app/share/codium/resources/app/out/vs/loader.js:5:101)
    at d.pb (/app/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:63164)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
[10:07:03 PM] [INFO] [002] Destroyed Discord RPC client
[10:07:03 PM] [INFO] Successfully logged in to Discord with client ID 1031067701474492496```

**Comment by SirFluffDev** [comment]
I solved the issue! Turns out I was using the Flatpak version of VSCodium. Manually installing the .deb provided by VSCodium's website fixed the issue.

**Comment by nick22985** [comment]
> [98db028](https://github.com/leonardssh/vscord/commit/98db028af5da06ef29f0926883bfae1d4e1b5643) should fix git issue.

Still happening more often now.

**Comment by KuezyIT** [comment]
Heyo, issue is now re-occuring with Visual Studio Code - Insiders:
```sh
[3:48:53 PM] [INFO] [data.ts] ext(): Extension
[3:48:53 PM] [INFO] [data.ts] ext(): Changed to Extension
[3:48:53 PM] [INFO] [data.ts] [data.ts] ext(): Git extension is active
[3:48:53 PM] [INFO] [data.ts] api(): true
[3:48:53 PM] [INFO] [data.ts] api(): gitApi
[3:48:53 PM] [INFO] [data.ts] updateGit()
[3:48:53 PM] [INFO] [data.ts] repo(): no file open
[3:48:53 PM] [INFO] [data.ts] gitRepoPath(): f:\Projects\Team Increase\General Management\12 Development
[3:48:53 PM] [INFO] [data.ts] updateGit(): repo f:\Projects\Team Increase\General Management\12 Development
[3:48:53 PM] [INFO] [data.ts] api(): true
[3:48:53 PM] [INFO] [data.ts] api(): gitApi
[3:48:53 PM] [INFO] [data.ts] updateGit()
[3:48:53 PM] [INFO] [data.ts] repo(): no file open
[3:48:53 PM] [INFO] [data.ts] gitRepoPath(): f:\Projects\Team Increase\General Management\12 Development
[3:48:53 PM] [INFO] [data.ts] updateGit(): repo f:\Projects\Team Increase\General Management\12 Development
[3:48:53 PM] [INFO] Discord Rich Presence for VS Code activated.
[3:48:53 PM] [INFO] Registered Discord Rich Presence commands
[3:48:58 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[3:49:02 PM] [INFO] Reconnecting to Discord Gateway...
[3:49:02 PM] [INFO] [004] Debug: Logging in with client ID "782685898163617802"
[3:49:02 PM] [INFO] [004] Debug: Login - isConnected false isReady 782685898163617802
[3:49:02 PM] [INFO] [004] Debug: login - [object Object]
[3:49:03 PM] [ERROR] Encountered following error while trying to login: RPC_CONNECTION_TIMEOUT: Connection timed out
    at $a.login (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.18\node_modules\.pnpm\@xhayper+discord-rpc@1.0.15\node_modules\@xhayper\discord-rpc\dist\Client.js:250:20)
    at new Zi (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.18\src\controller.ts:44:14)
    at Object.<anonymous> (c:\Users\kuezy\.vscode-insiders\extensions\leonardssh.vscord-5.0.18\src\extension.ts:10:20)
    at Module.u._compile (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.l._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:121:13353)
    at Function.b._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:61972)
    at Function.E._load (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:61365)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function.r [as __$__nodeRequire] (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:5:101)
    at f.pb (e:\Users\Kuezy\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:63236)
    at async Promise.all (index 0)
[3:49:03 PM] [INFO] [002] Destroyed Discord RPC client
[3:49:03 PM] [INFO] Successfully logged in to Discord with client ID 782685898163617802
[3:49:13 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[3:49:13 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'
[3:49:16 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[3:49:17 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor
[3:49:17 PM] [INFO] [data.ts] root(): window.onDidChangeActiveTextEditor: got unallowed scheme, got 'output'

```

**Comment by MatheusPese** [comment]
I was having the same issue, until I closed all discord instances (from other users in my machine) and restarted discord in my user. I don't know if it was what fixed it, but it is worth a try later. 
(Cannot try to reproduce it right now, as I am in someone else's computer)

**Comment by TheVoidlessHorizon** [comment]
Nothing in this thread has helped me. I believe it may be an issue with something on my end because none of the Discord RPC extensions work, but the bigger issue is actually finding what's causing the issue and fixing it.

**Comment by xhayper** [comment]
Latest version of VSCord should allow you to figure out whenever it cant find the Discord client, or have trouble connecting to the RPC server

**Comment by Mopsgamer** [comment]
I assume this problem is related to using multiple Discord windows. It is probably an RPC issue that expects only one instance.

Here is a likely reproduction:
- Open the first Discord instance
- Connect RPC
- Open the second Discord instance
- Close the first one
- Wait for the timeout
