### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by zachthedev** [leonardssh/vscord#302]
Details:
```
Name: Discord Rich Presence
Id: LeonardSSH.vscord
Description: Highly customizable Discord Rich Presence extension for Visual Studio Code
Version: 5.2.5
Publisher: leonardssh
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=LeonardSSH.vscord
```
I installed this and did not apply any configuration. I have not seen any status shown in Discord yet, and I only get this error in the Extension Host logger:
```
2024-04-03 18:23:28.059 [info] ExtensionService#_doActivateExtension LeonardSSH.vscord, startup: false, activationEvent: 'onStartupFinished'
2024-04-03 18:23:29.335 [error] TypeError: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:616:13)
    at replaceGitInfo (c:\Users\Zach\.vscode\extensions\leonardssh.vscord-5.2.5\src\activity.ts:416:52)
    at activity (c:\Users\Zach\.vscode\extensions\leonardssh.vscord-5.2.5\src\activity.ts:139:13)
    at pn.sendActivity (c:\Users\Zach\.vscode\extensions\leonardssh.vscord-5.2.5\src\controller.ts:194:28)
    at pn.enable (c:\Users\Zach\.vscode\extensions\leonardssh.vscord-5.2.5\src\controller.ts:221:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by leonardssh** [comment]
fixed in v5.2.6 (https://github.com/leonardssh/vscord/commit/a7b0205807a4a1ddfb3a3746aca1bf880b72a43e)
