### ISSUE TITLE
Extension throws an exception when used in cdr/code-server

### ISSUE THREAD

**Issue by quentincaffeino** [LeonardSSH/vscord#38]
Here's the exception:

```
[2021-11-18 20:55:03.124] [exthost] [info] ExtensionService#_doActivateExtension vscord-extension.vscord {"startup":false,"extensionId":{"value":"vscord-extension.vscord","_lower":"vscord-extension.vscord"},"activationEvent":"onStartupFinished"}
[2021-11-18 20:55:03.124] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js
[2021-11-18 20:55:03.434] [exthost] [error] Activating extension vscord-extension.vscord failed due to an error:
[2021-11-18 20:55:03.435] [exthost] [error] TypeError: Cannot read property 'write' of null
	at IPCTransport.send (/home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:2107:17)
	at /home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:2113:12
	at new Promise (<anonymous>)
	at IPCTransport.close (/home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:2111:12)
	at RPCClient.destroy (/home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:1710:26)
	at login (/home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:368:19)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
	at async activate (/home/quentincaffeino/.local/share/code-server/extensions/vscord-extension.vscord-4.1.6/dist/extension.js:460:9)
	at async Promise.all (index 0)
```

**Comment by LeonardSSH** [comment]
1. Make sure the discord is on when the extension is running.
2. Give extension a fresh install.
3. Restart vscode
4. Restart discord client

All of the above are possible fixes.

**Comment by quentincaffeino** [comment]
Ok sorry, I didn't know you need discord running for this, I thought it works through api. I run code-server on gui-less server so I would probably not be able to setup discord there. Thanks)
