### ISSUE TITLE
Not connecting to gateway

### ISSUE THREAD

**Issue by ronnie123442** [LeonardSSH/vscord#49]
[7:35:31 p.m. - INFO] [data.ts] ext(): Git extension is active
[7:35:31 p.m. - INFO] Initialize the extension...
[7:35:31 p.m. - ERROR] Could not connect
[7:35:31 p.m. - ERROR] Error: Could not connect
    at Socket.onerror (c:\Users\ronni\.vscode\extensions\leonardssh.vscord-4.4.0\node_modules\discord-rpc\src\transports\ipc.js:32:1)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by LeonardSSH** [comment]
1. Does the discord client run while you start the extension?
2. Where did you install the discord client?
3. Have you tried a fresh reinstall of the extension? 
4. have you tried restarting your discord? Even in **ran as administrator**?

**Comment by ronnie123442** [comment]
1. Yes
2. Default Location for discord (also tried with other versions like canary, ptb).
3. Yes, I've reinstalled it and tried multiple versions.
4. Yes

**Comment by LeonardSSH** [comment]
Please upgrade the extension and try again.

**Comment by ronnie123442** [comment]
It is now working.

**Comment by LeonardSSH** [comment]
I'm glad to hear that.
